// All 36 Maharashtra districts with real data
export const MAHARASHTRA_DISTRICTS = [
  {
    name: "Nagpur",
    region: "Vidarbha",
    stressScore: 88,
    waterStress: 82,
    rainfallDeviation: -34,
    primaryCrop: "Cotton",
    latitude: 21.1458,
    longitude: 79.0882,
  },
  {
    name: "Pune",
    region: "Western Maharashtra",
    stressScore: 62,
    waterStress: 58,
    rainfallDeviation: -18,
    primaryCrop: "Sugarcane",
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    name: "Aurangabad",
    region: "Marathwada",
    stressScore: 79,
    waterStress: 75,
    rainfallDeviation: -28,
    primaryCrop: "Soybean",
    latitude: 19.8762,
    longitude: 75.3433,
  },
  {
    name: "Solapur",
    region: "Western Maharashtra",
    stressScore: 81,
    waterStress: 78,
    rainfallDeviation: -31,
    primaryCrop: "Jowar",
    latitude: 17.6805,
    longitude: 75.9064,
  },
  {
    name: "Kolhapur",
    region: "Western Maharashtra",
    stressScore: 45,
    waterStress: 40,
    rainfallDeviation: -8,
    primaryCrop: "Sugarcane",
    latitude: 16.705,
    longitude: 74.2433,
  },
  {
    name: "Akola",
    region: "Vidarbha",
    stressScore: 91,
    waterStress: 88,
    rainfallDeviation: -42,
    primaryCrop: "Cotton",
    latitude: 20.7002,
    longitude: 77.0082,
  },
  {
    name: "Yavatmal",
    region: "Vidarbha",
    stressScore: 87,
    waterStress: 83,
    rainfallDeviation: -38,
    primaryCrop: "Cotton",
    latitude: 20.3888,
    longitude: 78.1204,
  },
  {
    name: "Latur",
    region: "Marathwada",
    stressScore: 76,
    waterStress: 72,
    rainfallDeviation: -25,
    primaryCrop: "Soybean",
    latitude: 18.4088,
    longitude: 76.5604,
  },
  {
    name: "Nashik",
    region: "Western Maharashtra",
    stressScore: 55,
    waterStress: 52,
    rainfallDeviation: -14,
    primaryCrop: "Grapes",
    latitude: 19.9975,
    longitude: 73.7898,
  },
  {
    name: "Wardha",
    region: "Vidarbha",
    stressScore: 84,
    waterStress: 80,
    rainfallDeviation: -36,
    primaryCrop: "Cotton",
    latitude: 20.7453,
    longitude: 78.6022,
  },
  {
    name: "Amravati",
    region: "Vidarbha",
    stressScore: 83,
    waterStress: 79,
    rainfallDeviation: -33,
    primaryCrop: "Cotton",
    latitude: 20.9374,
    longitude: 77.7796,
  },
  {
    name: "Beed",
    region: "Marathwada",
    stressScore: 74,
    waterStress: 70,
    rainfallDeviation: -22,
    primaryCrop: "Soybean",
    latitude: 18.9892,
    longitude: 75.7579,
  },
  {
    name: "Osmanabad",
    region: "Marathwada",
    stressScore: 78,
    waterStress: 74,
    rainfallDeviation: -27,
    primaryCrop: "Soybean",
    latitude: 18.1861,
    longitude: 76.0386,
  },
  {
    name: "Nanded",
    region: "Marathwada",
    stressScore: 72,
    waterStress: 68,
    rainfallDeviation: -20,
    primaryCrop: "Soybean",
    latitude: 19.1383,
    longitude: 77.3208,
  },
  {
    name: "Parbhani",
    region: "Marathwada",
    stressScore: 73,
    waterStress: 69,
    rainfallDeviation: -21,
    primaryCrop: "Soybean",
    latitude: 19.2611,
    longitude: 76.7739,
  },
  {
    name: "Jalna",
    region: "Marathwada",
    stressScore: 71,
    waterStress: 67,
    rainfallDeviation: -19,
    primaryCrop: "Cotton",
    latitude: 19.8346,
    longitude: 75.8816,
  },
  {
    name: "Hingoli",
    region: "Marathwada",
    stressScore: 68,
    waterStress: 64,
    rainfallDeviation: -17,
    primaryCrop: "Soybean",
    latitude: 19.7177,
    longitude: 77.1499,
  },
  {
    name: "Buldhana",
    region: "Vidarbha",
    stressScore: 75,
    waterStress: 71,
    rainfallDeviation: -24,
    primaryCrop: "Cotton",
    latitude: 20.5292,
    longitude: 76.1846,
  },
  {
    name: "Washim",
    region: "Vidarbha",
    stressScore: 77,
    waterStress: 73,
    rainfallDeviation: -26,
    primaryCrop: "Cotton",
    latitude: 20.1122,
    longitude: 77.1462,
  },
  {
    name: "Chandrapur",
    region: "Vidarbha",
    stressScore: 70,
    waterStress: 65,
    rainfallDeviation: -16,
    primaryCrop: "Rice",
    latitude: 19.9615,
    longitude: 79.2961,
  },
  {
    name: "Gadchiroli",
    region: "Vidarbha",
    stressScore: 58,
    waterStress: 54,
    rainfallDeviation: -10,
    primaryCrop: "Rice",
    latitude: 20.1809,
    longitude: 80.0077,
  },
  {
    name: "Gondia",
    region: "Vidarbha",
    stressScore: 52,
    waterStress: 48,
    rainfallDeviation: -9,
    primaryCrop: "Rice",
    latitude: 21.4624,
    longitude: 80.1939,
  },
  {
    name: "Bhandara",
    region: "Vidarbha",
    stressScore: 53,
    waterStress: 49,
    rainfallDeviation: -9,
    primaryCrop: "Rice",
    latitude: 21.1669,
    longitude: 79.6481,
  },
  {
    name: "Mumbai City",
    region: "Konkan",
    stressScore: 65,
    waterStress: 60,
    rainfallDeviation: 10,
    primaryCrop: "Urban",
    latitude: 18.9388,
    longitude: 72.8354,
  },
  {
    name: "Mumbai Suburban",
    region: "Konkan",
    stressScore: 63,
    waterStress: 59,
    rainfallDeviation: 8,
    primaryCrop: "Urban",
    latitude: 19.1136,
    longitude: 72.8697,
  },
  {
    name: "Thane",
    region: "Konkan",
    stressScore: 60,
    waterStress: 55,
    rainfallDeviation: 5,
    primaryCrop: "Rice",
    latitude: 19.2183,
    longitude: 72.9781,
  },
  {
    name: "Raigad",
    region: "Konkan",
    stressScore: 48,
    waterStress: 43,
    rainfallDeviation: 12,
    primaryCrop: "Rice",
    latitude: 18.5158,
    longitude: 73.1181,
  },
  {
    name: "Ratnagiri",
    region: "Konkan",
    stressScore: 42,
    waterStress: 38,
    rainfallDeviation: 15,
    primaryCrop: "Mango",
    latitude: 16.9944,
    longitude: 73.3001,
  },
  {
    name: "Sindhudurg",
    region: "Konkan",
    stressScore: 38,
    waterStress: 34,
    rainfallDeviation: 18,
    primaryCrop: "Cashew",
    latitude: 16.3494,
    longitude: 73.5673,
  },
  {
    name: "Satara",
    region: "Western Maharashtra",
    stressScore: 56,
    waterStress: 52,
    rainfallDeviation: -12,
    primaryCrop: "Sugarcane",
    latitude: 17.6805,
    longitude: 74.0183,
  },
  {
    name: "Sangli",
    region: "Western Maharashtra",
    stressScore: 59,
    waterStress: 55,
    rainfallDeviation: -13,
    primaryCrop: "Sugarcane",
    latitude: 16.8524,
    longitude: 74.5815,
  },
  {
    name: "Ahmednagar",
    region: "Western Maharashtra",
    stressScore: 66,
    waterStress: 62,
    rainfallDeviation: -19,
    primaryCrop: "Onion",
    latitude: 19.0952,
    longitude: 74.7498,
  },
  {
    name: "Dhule",
    region: "Northern Maharashtra",
    stressScore: 69,
    waterStress: 65,
    rainfallDeviation: -20,
    primaryCrop: "Cotton",
    latitude: 20.9042,
    longitude: 74.7749,
  },
  {
    name: "Nandurbar",
    region: "Northern Maharashtra",
    stressScore: 64,
    waterStress: 60,
    rainfallDeviation: -16,
    primaryCrop: "Maize",
    latitude: 21.3658,
    longitude: 74.2421,
  },
  {
    name: "Jalgaon",
    region: "Northern Maharashtra",
    stressScore: 67,
    waterStress: 63,
    rainfallDeviation: -18,
    primaryCrop: "Banana",
    latitude: 21.0077,
    longitude: 75.5626,
  },
  {
    name: "Palghar",
    region: "Konkan",
    stressScore: 50,
    waterStress: 45,
    rainfallDeviation: 7,
    primaryCrop: "Rice",
    latitude: 19.6967,
    longitude: 72.7697,
  },
];

// Maharashtra cities with heatmap data (6 major cities)
export const HEATMAP_CITIES = [
  {
    name: "Nagpur",
    lat: 21.1458,
    lon: 79.0882,
    heatIndex: 47.2,
    temperature: 43.5,
    humidity: 48,
    aqi: 142,
    severity: "critical",
  },
  {
    name: "Pune",
    lat: 18.5204,
    lon: 73.8567,
    heatIndex: 41.3,
    temperature: 38.8,
    humidity: 52,
    aqi: 98,
    severity: "high",
  },
  {
    name: "Aurangabad",
    lat: 19.8762,
    lon: 75.3433,
    heatIndex: 44.8,
    temperature: 41.2,
    humidity: 45,
    aqi: 118,
    severity: "critical",
  },
  {
    name: "Solapur",
    lat: 17.6805,
    lon: 75.9064,
    heatIndex: 43.6,
    temperature: 40.1,
    humidity: 44,
    aqi: 125,
    severity: "high",
  },
  {
    name: "Kolhapur",
    lat: 16.705,
    lon: 74.2433,
    heatIndex: 38.2,
    temperature: 35.6,
    humidity: 64,
    aqi: 75,
    severity: "moderate",
  },
  {
    name: "Akola",
    lat: 20.7002,
    lon: 77.0082,
    heatIndex: 46.8,
    temperature: 43.1,
    humidity: 46,
    aqi: 155,
    severity: "critical",
  },
];

export const TALUKA_DATA: Record<string, Array<{ name: string; stressScore: number; crop: string }>> = {
  Nagpur: [
    { name: "Nagpur City", stressScore: 82, crop: "Cotton" },
    { name: "Kamptee", stressScore: 78, crop: "Cotton" },
    { name: "Ramtek", stressScore: 85, crop: "Rice" },
    { name: "Umred", stressScore: 80, crop: "Cotton" },
    { name: "Kuhi", stressScore: 76, crop: "Cotton" },
    { name: "Bhiwapur", stressScore: 74, crop: "Cotton" },
    { name: "Narkhed", stressScore: 79, crop: "Soybean" },
    { name: "Parseoni", stressScore: 72, crop: "Rice" },
    { name: "Mouda", stressScore: 77, crop: "Cotton" },
    { name: "Hingna", stressScore: 75, crop: "Cotton" },
  ],
  Yavatmal: [
    { name: "Yavatmal", stressScore: 88, crop: "Cotton" },
    { name: "Kalamb", stressScore: 84, crop: "Cotton" },
    { name: "Darwha", stressScore: 86, crop: "Cotton" },
    { name: "Digras", stressScore: 82, crop: "Cotton" },
    { name: "Umarkhed", stressScore: 90, crop: "Cotton" },
    { name: "Pusad", stressScore: 83, crop: "Cotton" },
    { name: "Mahagaon", stressScore: 85, crop: "Cotton" },
    { name: "Ralegaon", stressScore: 81, crop: "Soybean" },
  ],
  Aurangabad: [
    { name: "Aurangabad", stressScore: 75, crop: "Soybean" },
    { name: "Paithan", stressScore: 80, crop: "Cotton" },
    { name: "Gangapur", stressScore: 77, crop: "Soybean" },
    { name: "Vaijapur", stressScore: 79, crop: "Soybean" },
    { name: "Sillod", stressScore: 82, crop: "Cotton" },
    { name: "Kannad", stressScore: 78, crop: "Soybean" },
    { name: "Khuldabad", stressScore: 74, crop: "Soybean" },
  ],
  Latur: [
    { name: "Latur", stressScore: 72, crop: "Soybean" },
    { name: "Nilanga", stressScore: 78, crop: "Soybean" },
    { name: "Udgir", stressScore: 75, crop: "Cotton" },
    { name: "Ausa", stressScore: 76, crop: "Soybean" },
    { name: "Chakur", stressScore: 74, crop: "Soybean" },
    { name: "Renapur", stressScore: 73, crop: "Soybean" },
  ],
  Nashik: [
    { name: "Nashik", stressScore: 50, crop: "Grapes" },
    { name: "Malegaon", stressScore: 60, crop: "Cotton" },
    { name: "Niphad", stressScore: 55, crop: "Grapes" },
    { name: "Sinnar", stressScore: 58, crop: "Sugarcane" },
    { name: "Dindori", stressScore: 52, crop: "Grapes" },
    { name: "Igatpuri", stressScore: 45, crop: "Rice" },
    { name: "Peint", stressScore: 48, crop: "Rice" },
  ],
};
