export type Division =
  | "Konkan"
  | "Nashik"
  | "Pune"
  | "Aurangabad"
  | "Amravati"
  | "Nagpur";

export interface District {
  id: string;
  name: string;
  code: string;
  division: Division;
  lat: number;
  lng: number;
  area: number;
  population: number;
  stressScore: number;
  waterStress: number;
  cropDamageRisk: number;
  talukas: string[];
}

export const DISTRICTS: District[] = [
  {
    id: "nashik",
    name: "Nashik",
    code: "NSK",
    division: "Nashik",
    lat: 20.0112,
    lng: 73.7908,
    area: 15530,
    population: 6107187,
    stressScore: 62,
    waterStress: 58,
    cropDamageRisk: 55,
    talukas: ["Nashik", "Niphad", "Sinnar", "Igatpuri", "Dindori", "Kalwan", "Surgana", "Trimbakeshwar", "Yeola", "Chandwad", "Nandgaon", "Malegaon", "Baglan", "Deola"],
  },
  {
    id: "pune",
    name: "Pune",
    code: "PNE",
    division: "Pune",
    lat: 18.5204,
    lng: 73.8567,
    area: 15643,
    population: 9429408,
    stressScore: 55,
    waterStress: 50,
    cropDamageRisk: 48,
    talukas: ["Pune City", "Haveli", "Mulshi", "Maval", "Khed", "Junnar", "Ambegaon", "Shirur", "Daund", "Indapur", "Baramati", "Purandar", "Bhor", "Velhe"],
  },
  {
    id: "mumbai-suburban",
    name: "Mumbai Suburban",
    code: "MSB",
    division: "Konkan",
    lat: 19.0760,
    lng: 72.8777,
    area: 446,
    population: 9356962,
    stressScore: 70,
    waterStress: 72,
    cropDamageRisk: 30,
    talukas: ["Andheri", "Borivali", "Kurla"],
  },
  {
    id: "thane",
    name: "Thane",
    code: "THN",
    division: "Konkan",
    lat: 19.2183,
    lng: 72.9781,
    area: 9921,
    population: 11060148,
    stressScore: 65,
    waterStress: 60,
    cropDamageRisk: 45,
    talukas: ["Thane", "Kalyan", "Ulhasnagar", "Bhiwandi", "Shahapur", "Murbad", "Ambernath", "Mhasala"],
  },
  {
    id: "palghar",
    name: "Palghar",
    code: "PLG",
    division: "Konkan",
    lat: 19.6967,
    lng: 72.7697,
    area: 5344,
    population: 2990116,
    stressScore: 60,
    waterStress: 55,
    cropDamageRisk: 65,
    talukas: ["Palghar", "Vasai", "Dahanu", "Talasari", "Jawhar", "Mokhada", "Vikramgad", "Wada"],
  },
  {
    id: "raigad",
    name: "Raigad",
    code: "RGD",
    division: "Konkan",
    lat: 18.5158,
    lng: 73.1773,
    area: 7152,
    population: 2634200,
    stressScore: 52,
    waterStress: 48,
    cropDamageRisk: 50,
    talukas: ["Alibag", "Pen", "Panvel", "Karjat", "Khalapur", "Mahad", "Poladpur", "Mangaon", "Tala", "Roha", "Murud", "Shrivardhan", "Mhasla", "Uran", "Sudhagad"],
  },
  {
    id: "ratnagiri",
    name: "Ratnagiri",
    code: "RTN",
    division: "Konkan",
    lat: 16.9944,
    lng: 73.3001,
    area: 8208,
    population: 1615069,
    stressScore: 45,
    waterStress: 42,
    cropDamageRisk: 60,
    talukas: ["Ratnagiri", "Sangameshwar", "Lanja", "Rajapur", "Chiplun", "Guhagar", "Dapoli", "Mandangad", "Khed"],
  },
  {
    id: "sindhudurg",
    name: "Sindhudurg",
    code: "SDG",
    division: "Konkan",
    lat: 16.3524,
    lng: 73.6486,
    area: 5207,
    population: 849651,
    stressScore: 40,
    waterStress: 38,
    cropDamageRisk: 55,
    talukas: ["Kudal", "Malvan", "Sawantwadi", "Vengurla", "Kankavli", "Vaibhavwadi", "Devgad", "Dodamarg"],
  },
  {
    id: "kolhapur",
    name: "Kolhapur",
    code: "KLP",
    division: "Pune",
    lat: 16.7050,
    lng: 74.2433,
    area: 7685,
    population: 3876001,
    stressScore: 48,
    waterStress: 45,
    cropDamageRisk: 52,
    talukas: ["Kolhapur", "Karveer", "Panhala", "Shirol", "Kagal", "Hatkanangle", "Shahuwadi", "Gadhinglaj", "Chandgad", "Ajra", "Bavda", "Radhanagari"],
  },
  {
    id: "sangli",
    name: "Sangli",
    code: "SNG",
    division: "Pune",
    lat: 16.8524,
    lng: 74.5815,
    area: 8572,
    population: 2820575,
    stressScore: 58,
    waterStress: 62,
    cropDamageRisk: 55,
    talukas: ["Miraj", "Sangli", "Walwa", "Shirala", "Tasgaon", "Jat", "Khanapur", "Atpadi", "Kavathemahankal", "Palus"],
  },
  {
    id: "satara",
    name: "Satara",
    code: "STR",
    division: "Pune",
    lat: 17.6805,
    lng: 74.0183,
    area: 10484,
    population: 3003741,
    stressScore: 50,
    waterStress: 55,
    cropDamageRisk: 48,
    talukas: ["Satara", "Karad", "Khatav", "Koregaon", "Man", "Mahabaleshwar", "Patan", "Phaltan", "Jaoli", "Wai", "Khandala"],
  },
  {
    id: "solapur",
    name: "Solapur",
    code: "SLP",
    division: "Pune",
    lat: 17.6868,
    lng: 75.9064,
    area: 14895,
    population: 4317756,
    stressScore: 78,
    waterStress: 80,
    cropDamageRisk: 75,
    talukas: ["Solapur North", "Solapur South", "Akkalkot", "Barshi", "Karmala", "Madha", "Mangalvedha", "Mohol", "Pandharpur", "Sangola", "Malshiras", "North Solapur", "South Solapur"],
  },
  {
    id: "ahmednagar",
    name: "Ahmednagar",
    code: "ANG",
    division: "Nashik",
    lat: 19.0952,
    lng: 74.7496,
    area: 17048,
    population: 4543083,
    stressScore: 72,
    waterStress: 75,
    cropDamageRisk: 68,
    talukas: ["Ahmednagar", "Akole", "Jamkhed", "Karjat", "Kopargaon", "Nevasa", "Parner", "Pathardi", "Rahata", "Rahuri", "Sangamner", "Shevgaon", "Shrigonda", "Shrirampur"],
  },
  {
    id: "aurangabad",
    name: "Aurangabad (Chhatrapati Sambhajinagar)",
    code: "AUR",
    division: "Aurangabad",
    lat: 19.8762,
    lng: 75.3433,
    area: 10100,
    population: 3701282,
    stressScore: 74,
    waterStress: 70,
    cropDamageRisk: 72,
    talukas: ["Aurangabad", "Kannad", "Khuldabad", "Gangapur", "Paithan", "Sillod", "Soegaon", "Vaijapur", "Phulambri"],
  },
  {
    id: "jalna",
    name: "Jalna",
    code: "JLN",
    division: "Aurangabad",
    lat: 19.8347,
    lng: 75.8816,
    area: 7718,
    population: 1959046,
    stressScore: 68,
    waterStress: 65,
    cropDamageRisk: 70,
    talukas: ["Jalna", "Ambad", "Badnapur", "Bhokardan", "Ghansawangi", "Jafrabad", "Mantha", "Partur"],
  },
  {
    id: "beed",
    name: "Beed",
    code: "BED",
    division: "Aurangabad",
    lat: 18.9891,
    lng: 75.7601,
    area: 10693,
    population: 2585962,
    stressScore: 80,
    waterStress: 82,
    cropDamageRisk: 78,
    talukas: ["Beed", "Ambejogai", "Dharur", "Gevrai", "Kaij", "Parli", "Patoda", "Shirur (Kasar)", "Ashti", "Manjlegaon"],
  },
  {
    id: "latur",
    name: "Latur",
    code: "LTR",
    division: "Aurangabad",
    lat: 18.4088,
    lng: 76.5604,
    area: 7157,
    population: 2454196,
    stressScore: 75,
    waterStress: 78,
    cropDamageRisk: 72,
    talukas: ["Latur", "Ahmadpur", "Ausa", "Chakur", "Deoni", "Jalkot", "Nilanga", "Renapur", "Shirur Anantpal", "Udgir"],
  },
  {
    id: "osmanabad",
    name: "Osmanabad (Dharashiv)",
    code: "OSM",
    division: "Aurangabad",
    lat: 18.1861,
    lng: 76.0406,
    area: 7569,
    population: 1657576,
    stressScore: 76,
    waterStress: 74,
    cropDamageRisk: 73,
    talukas: ["Osmanabad", "Bhum", "Kalamb", "Lohara", "Paranda", "Tuljapur", "Umarga", "Washi"],
  },
  {
    id: "nanded",
    name: "Nanded",
    code: "NND",
    division: "Aurangabad",
    lat: 19.1383,
    lng: 77.3210,
    area: 10528,
    population: 3357709,
    stressScore: 65,
    waterStress: 68,
    cropDamageRisk: 62,
    talukas: ["Nanded", "Ardhapur", "Biloli", "Deglur", "Dharmabad", "Hadgaon", "Himayatnagar", "Kandhar", "Kinwat", "Loha", "Mahoor", "Mudkhed", "Mukhed", "Naigaon (Khairgaon)", "Umri"],
  },
  {
    id: "hingoli",
    name: "Hingoli",
    code: "HNG",
    division: "Aurangabad",
    lat: 19.7177,
    lng: 77.1499,
    area: 4526,
    population: 1177345,
    stressScore: 62,
    waterStress: 60,
    cropDamageRisk: 65,
    talukas: ["Hingoli", "Aundha Nagnath", "Basmath", "Kalamnuri", "Sengaon"],
  },
  {
    id: "parbhani",
    name: "Parbhani",
    code: "PRB",
    division: "Aurangabad",
    lat: 19.2704,
    lng: 76.7747,
    area: 6511,
    population: 1836086,
    stressScore: 66,
    waterStress: 64,
    cropDamageRisk: 68,
    talukas: ["Parbhani", "Gangakhed", "Jintur", "Manwath", "Palam", "Pathri", "Purna", "Sailu", "Sonpeth"],
  },
  {
    id: "washim",
    name: "Washim",
    code: "WSM",
    division: "Amravati",
    lat: 20.1120,
    lng: 77.1333,
    area: 5150,
    population: 1196714,
    stressScore: 70,
    waterStress: 68,
    cropDamageRisk: 72,
    talukas: ["Washim", "Karanja", "Malegaon", "Mangrulpir", "Manora", "Risod"],
  },
  {
    id: "akola",
    name: "Akola",
    code: "AKL",
    division: "Amravati",
    lat: 20.7002,
    lng: 77.0082,
    area: 5428,
    population: 1818617,
    stressScore: 73,
    waterStress: 70,
    cropDamageRisk: 74,
    talukas: ["Akola", "Akot", "Balapur", "Barshitakli", "Murtajapur", "Patur", "Telhara"],
  },
  {
    id: "amravati",
    name: "Amravati",
    code: "AMR",
    division: "Amravati",
    lat: 20.9374,
    lng: 77.7796,
    area: 12235,
    population: 2888445,
    stressScore: 67,
    waterStress: 65,
    cropDamageRisk: 70,
    talukas: ["Amravati", "Achalpur", "Anjangaon Surji", "Bhatkuli", "Chandur Bazar", "Chandur Railway", "Chikhaldara", "Daryapur", "Dhamangaon Railway", "Morshi", "Nandgaon Khandeshwar", "Tiwsa", "Warud"],
  },
  {
    id: "buldhana",
    name: "Buldhana",
    code: "BLD",
    division: "Amravati",
    lat: 20.5292,
    lng: 76.1842,
    area: 9661,
    population: 2587692,
    stressScore: 64,
    waterStress: 66,
    cropDamageRisk: 60,
    talukas: ["Buldhana", "Chikhli", "Deulgaon Raja", "Jalgaon (Jamod)", "Khamgaon", "Lonar", "Malkapur", "Mehkar", "Motala", "Nandura", "Sangrampur", "Shegaon", "Sindkhed Raja"],
  },
  {
    id: "yavatmal",
    name: "Yavatmal",
    code: "YVT",
    division: "Amravati",
    lat: 20.3888,
    lng: 78.1204,
    area: 13582,
    population: 2772348,
    stressScore: 71,
    waterStress: 69,
    cropDamageRisk: 76,
    talukas: ["Yavatmal", "Arni", "Babulgaon", "Darwha", "Digras", "Ghatanji", "Kalamb", "Kelapur", "Mahagaon", "Maregaon", "Ner", "Pusad", "Ralegaon", "Umarkhed", "Wani", "Zari Jamni"],
  },
  {
    id: "wardha",
    name: "Wardha",
    code: "WRD",
    division: "Nagpur",
    lat: 20.7453,
    lng: 78.6022,
    area: 6309,
    population: 1300774,
    stressScore: 60,
    waterStress: 58,
    cropDamageRisk: 62,
    talukas: ["Wardha", "Arvi", "Ashti", "Deoli", "Hinganghat", "Karanja", "Samudrapur", "Seloo"],
  },
  {
    id: "nagpur",
    name: "Nagpur",
    code: "NGP",
    division: "Nagpur",
    lat: 21.1458,
    lng: 79.0882,
    area: 9892,
    population: 4653570,
    stressScore: 69,
    waterStress: 65,
    cropDamageRisk: 58,
    talukas: ["Nagpur Urban", "Nagpur Rural", "Hingna", "Kamptee", "Katol", "Kuhi", "Mauda", "Narkhed", "Parseoni", "Ramtek", "Savner", "Umred"],
  },
  {
    id: "bhandara",
    name: "Bhandara",
    code: "BHN",
    division: "Nagpur",
    lat: 21.1664,
    lng: 79.6479,
    area: 3717,
    population: 1200334,
    stressScore: 50,
    waterStress: 48,
    cropDamageRisk: 55,
    talukas: ["Bhandara", "Lakhandur", "Lakhani", "Mohadi", "Pauni", "Sakoli", "Tumsar"],
  },
  {
    id: "gondia",
    name: "Gondia",
    code: "GND",
    division: "Nagpur",
    lat: 21.4602,
    lng: 80.1919,
    area: 5234,
    population: 1322507,
    stressScore: 45,
    waterStress: 42,
    cropDamageRisk: 50,
    talukas: ["Gondia", "Amgaon", "Arjuni Morgaon", "Deori", "Goregaon", "Sadak Arjuni", "Salekasa", "Tirora"],
  },
  {
    id: "chandrapur",
    name: "Chandrapur",
    code: "CDP",
    division: "Nagpur",
    lat: 19.9615,
    lng: 79.2961,
    area: 11443,
    population: 2204307,
    stressScore: 63,
    waterStress: 60,
    cropDamageRisk: 65,
    talukas: ["Chandrapur", "Ballarpur", "Bhadravati", "Brahmapuri", "Chimur", "Gondpipri", "Jivati", "Korpana", "Mul", "Nagbhid", "Pombhurna", "Rajura", "Sawali", "Sindewahi", "Warora"],
  },
  {
    id: "gadchiroli",
    name: "Gadchiroli",
    code: "GDC",
    division: "Nagpur",
    lat: 20.1803,
    lng: 80.0000,
    area: 14412,
    population: 1072942,
    stressScore: 42,
    waterStress: 40,
    cropDamageRisk: 45,
    talukas: ["Gadchiroli", "Aheri", "Armori", "Bhamragad", "Chamorshi", "Dhanora", "Desaiganj (Vadasa)", "Etapalli", "Korchi", "Kurkheda", "Mulchera", "Sironcha"],
  },
  {
    id: "mumbai-city",
    name: "Mumbai City",
    code: "MUM",
    division: "Konkan",
    lat: 18.9388,
    lng: 72.8354,
    area: 157,
    population: 3085411,
    stressScore: 72,
    waterStress: 74,
    cropDamageRisk: 20,
    talukas: ["Mumbai City"],
  },
  {
    id: "dhule",
    name: "Dhule",
    code: "DHL",
    division: "Nashik",
    lat: 20.9042,
    lng: 74.7749,
    area: 7195,
    population: 2050862,
    stressScore: 69,
    waterStress: 72,
    cropDamageRisk: 65,
    talukas: ["Dhule", "Sakri", "Shirpur", "Sindkheda"],
  },
  {
    id: "jalgaon",
    name: "Jalgaon",
    code: "JLG",
    division: "Nashik",
    lat: 21.0077,
    lng: 75.5626,
    area: 11765,
    population: 4229917,
    stressScore: 74,
    waterStress: 76,
    cropDamageRisk: 70,
    talukas: ["Jalgaon", "Amalner", "Bhadgaon", "Bhusawal", "Bodwad", "Chalisgaon", "Chopda", "Erandol", "Jamner", "Muktainagar", "Pachora", "Parola", "Raver", "Yawal"],
  },
  {
    id: "nandurbar",
    name: "Nandurbar",
    code: "NDB",
    division: "Nashik",
    lat: 21.3682,
    lng: 74.2410,
    area: 5055,
    population: 1648295,
    stressScore: 66,
    waterStress: 70,
    cropDamageRisk: 68,
    talukas: ["Nandurbar", "Navapur", "Shahada", "Taloda", "Akkalkuwa", "Akrani"],
  },
];

export function getDistrictById(id: string): District | undefined {
  return DISTRICTS.find((d) => d.id === id);
}

export function getDistrictsByDivision(division: Division): District[] {
  return DISTRICTS.filter((d) => d.division === division);
}

export function getHighStressDistricts(threshold = 70): District[] {
  return DISTRICTS.filter((d) => d.stressScore >= threshold);
}

export const DIVISIONS: Division[] = [
  "Konkan",
  "Nashik",
  "Pune",
  "Aurangabad",
  "Amravati",
  "Nagpur",
];
