import { NextRequest, NextResponse } from "next/server";
import { getGroqClient } from "@/lib/groq";
import { DISTRICTS } from "@/lib/districts";

export async function POST(req: NextRequest) {
  try {
    const { districtId, category, prompt } = await req.json();
    const district = districtId ? DISTRICTS.find((d) => d.id === districtId) : null;

    // Sanitize user prompt: strip control chars, prompt-injection patterns, and limit length
    const sanitizedPrompt = prompt
      ? String(prompt)
          .replace(/[<>{}[\]\\]/g, "")
          // Remove common injection patterns (ignore/override/system instructions)
          .replace(/\b(ignore|override|forget|disregard|system|instruction|previous|above)\b/gi, "")
          .slice(0, 300)
      : "";

    const groq = getGroqClient();
    if (!groq) {
      // Fallback mock policy
      const mockContent = `## ${category} Policy for ${district?.name || "Maharashtra"}

### Overview
Based on current heat stress analysis (Score: ${district?.stressScore ?? 70}/100) and water stress indicators (${district?.waterStress ?? 65}/100), the following policy framework is recommended.

### Key Measures
1. **Immediate Action**: Deploy heat mitigation resources within 48 hours
2. **Water Conservation**: Implement micro-irrigation across affected talukas
3. **Farmer Support**: Activate crop insurance claims and provide emergency credit
4. **Public Health**: Open cooling centers in major towns; distribute ORS packets

### Implementation Timeline
- Week 1-2: Assessment and resource mobilization
- Week 3-4: Field deployment and monitoring
- Month 2-3: Evaluation and course correction

### Budget Estimate
Estimated cost: ₹2.5 crore for district-level implementation

*Generated by CascadeCity AI (mock - no API key configured)*`;

      return NextResponse.json({
        content: mockContent,
        category,
        districtId,
        aiGenerated: true,
      });
    }

    const contextPrompt = district
      ? `Generate a detailed government policy for ${district.name} district (Division: ${district.division}). 
         Current metrics: Heat Stress Score ${district.stressScore}/100, Water Stress ${district.waterStress}/100, Crop Damage Risk ${district.cropDamageRisk}/100.
         Category: ${category}. ${sanitizedPrompt}`
      : `Generate a detailed government policy for Maharashtra state. Category: ${category}. ${sanitizedPrompt}`;

    const completion = await groq.chat.completions.create({
      model: "llama-3.1-70b-versatile",
      messages: [
        {
          role: "system",
          content:
            "You are a Maharashtra government policy expert. Generate detailed, actionable government policies in structured format with sections for Overview, Objectives, Key Measures, Implementation Timeline, Budget, and Monitoring.",
        },
        { role: "user", content: contextPrompt },
      ],
      max_tokens: 1000,
    });

    const content = completion.choices[0]?.message?.content || "";
    return NextResponse.json({ content, category, districtId, aiGenerated: true });
  } catch {
    return NextResponse.json({ error: "Failed to generate policy" }, { status: 500 });
  }
}
